### ISSUE TITLE
Node-RED

### ISSUE THREAD

**Issue by pidpawel** [jerosoler/IoTFlow#5]
Hi!
This is not an issue per se, more of a notification that there is a tool named [Node-RED](https://nodered.org/) that looks very similar to the one in your demo. I couldn't find any high-level information about your project so I was unable to guess whether you're aware of it. Feel free to close this issue without a comment :-P

--
Have fun
pidpawel

**Comment by jerosoler** [comment]
Hi @pidpawel 

Yes, i know Node-red. This is old personal project for my home.

I have a library called Drawflow (https://github.com/jerosoler/Drawflow), for creating data flow similar to Node-Red.

Thanks for you reply. 

I hope you liked the project.

Jero
